### ISSUE TITLE
Paper comments

### ISSUE THREAD

**Issue by ksil91** [kubu4/paper_oly_gbs#10]
Not sure how you want comments on draft...
- I think the restriction cutsite is usually referred to as G^CWGC (if it is referred to at all)
- Did BGI do any fragment size selection prior to sequencing? If so, people would want to know before using that data, and would want to know if it was done with a PippinPrep or by hand

**Comment by kubu4** [comment]
Thanks. Comments here are fine or Authorea if that's easier.

**Comment by kubu4** [comment]
- I referred to the cut site using that nomenclature because that's how it is referred to in the reference for the technique.

- No fragement size selection, however, library sizes are evaluated prior to running on the HiSeq (also in the reference for the technique).

Ref is here, if you're interested: http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0019379
