### ISSUE TITLE
SRA: Raw FASTQ or demultiplexed?

### ISSUE THREAD

**Issue by kubu4** [kubu4/paper_oly_gbs#2]
Need to get the FASTQs in the SRA, but not sure if we should submit the demultiplexed FASTQS or the raw FASTQs.

Initially was leaning towards the two raw FASTQ files, but I'm not sure how we'd provide demultiplexing info to the SRA...

**Comment by jldimond** [comment]
Sam - I just happened to find this post from a Google search of "demulitplex SRA" since I am uploading some RADseq data. It sounds like SRA wants demultiplexed data:

"The SRA data model has transitioned from “dumps” of whole flowcell lanes or production runs into a semi-curated database of sample-specific sequencing libraries. This has implications for the types of data that we accept. Most specifically, barcoded/batch files should be split into per-sample data files (“demultiplexed”). Demultiplexing makes the sample - data linkage unambiguous in our database and should improve both the clarity and usability of submitted data. Please email vog.hin.mln.ibcn@ars if you have specific questions about data requirements vis-à-vis samples."

From https://www.ncbi.nlm.nih.gov/books/NBK242622/

**Comment by kubu4** [comment]
Nice find! Thanks for this!

**Comment by StuntsPT** [comment]
I just wanted to pitch in with a "thank you" note. Finding this information was not easy, so thank you for posting it here.
